# Generated by Django 3.1.3 on 2021-02-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='refresh',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
