# Generated by Django 3.1.3 on 2021-02-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210220_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UsersToken',
        ),
    ]
