# Generated by Django 3.1.7 on 2021-02-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210225_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True),
        ),
    ]
