# Generated by Django 3.1.3 on 2021-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210225_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
