# Generated by Django 3.1.7 on 2021-04-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210310_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado: Prohibido modificar este campo.'),
        ),
    ]
